---
- name: Make python3 default
  alternatives:
     name: python
     path: /usr/bin/python3
     link: /usr/bin/python
     priority: 10
  become: yes

- name: Setting Sysctl
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  become: yes

- name: Nat for Masquerade
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth0
    jump: MASQUERADE
    comment: Natting for Exit Nodes
  become: yes

- name: Copy the WireGuard Configuration 
  copy:
    src: "files/{{ file }}"
    dest: /etc/wireguard/wg0.conf

- name: Start the WireGuard Service
  ansible.builtin.service:
    name: wg-quick@wg0.service
    state: started
    enabled: true
  become: yes