---
- name: Make python3 default
  alternatives:
     name: python
     path: /usr/bin/python3
     link: /usr/bin/python
     priority: 10
  become: yes

- name: Run the existing installation file
  raw: "cd /root; /root/install.sh"
  become: yes

- name: Copy key files to server
  copy:
    src: files/
    dest: /etc/openvpn/server/
  become: yes

- name: Hack to force the new service
  raw: "systemctl enable -f openvpn-server@server.service"
  become: yes

- name: Start service openvpn, if not started
  ansible.builtin.service:
    name: openvpn-server@server.service
    state: started
  become: yes