---
- name: Make python3 default
  alternatives:
     name: python
     path: /usr/bin/python3
     link: /usr/bin/python
     priority: 10
  become: yes

- name: Run the existing installation file
  raw: "cd /root; /root/install.sh"
  become: yes

- name: Setup secondary route table
  ansible.builtin.lineinfile:
    name: "/etc/iproute2/rt_tables"
    line: "50	loadb"
    state: present
  register: loadb_conf

- name: Copy ip_rule file to server
  copy:
    src: files/ip_rule.sh
    dest: /root/ip_rule.sh
    mode: '0700'
  notify: run ip_rule
  become: yes

- name: Setting Sysctl
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Setting Sysctl
  ansible.posix.sysctl:
    name: net.ipv4.fib_multipath_hash_policy
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Copying files
  copy: 
    src: "{{ item }}"
    dest: /etc/wireguard/
  with_fileglob:
    - "exit-node*.conf"

- name: Copy bring-up-nodes file to server
  copy:
    src: files/bring-up-nodes.sh
    dest: /root/bring-up-nodes.sh
    mode: '0700'
  notify: run bring-up-nodes
  become: yes